// <auto-generated />
using System;
using BShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BShop.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BShop.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UpdatedID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b22698b8-42a2-4115-9631-1c2d1e2ac5f7"),
                            AccessFailedCount = 0,
                            Active = true,
                            ConcurrencyStamp = "b27c53ef-1b8c-4f0a-922a-43af90e8d493",
                            CreatedID = new Guid("b22698b8-42a2-4115-9631-1c2d1e2ac5f7"),
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@bshop.com",
                            EmailConfirmed = true,
                            FullName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BSHOP.COM",
                            NormalizedUserName = "ADMIN@BSHOP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF56DmfAObjRWfsPMzcojT5Xxl+xwnQoncgN0855J1aPpA15i0PngiW6gyAAQkmtoQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "22a57152-720b-44df-aee6-4c6b44e56a3e",
                            TwoFactorEnabled = false,
                            UserName = "admin@bshop.com"
                        },
                        new
                        {
                            Id = new Guid("c7bc5cc5-d2df-43e5-bf6e-95f88bb9ee6a"),
                            AccessFailedCount = 0,
                            Active = true,
                            ConcurrencyStamp = "9d125903-df64-4c00-bd26-bdb39657c38b",
                            CreatedID = new Guid("c7bc5cc5-d2df-43e5-bf6e-95f88bb9ee6a"),
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "seller@bshop.com",
                            EmailConfirmed = true,
                            FullName = "Gorigor",
                            LockoutEnabled = false,
                            NormalizedEmail = "Seller@BSHOP.COM",
                            NormalizedUserName = "SELLER@BSHOP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED96CADbnMTUY5zBULNbCepEY53C5stLwnUN/dhMLRMYZydKsauWvBqqldebgCw0qQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "571f0fbf-532d-408b-8386-884e7bb567ed",
                            TwoFactorEnabled = false,
                            UserName = "Seller@bshop.com"
                        },
                        new
                        {
                            Id = new Guid("aab46b7a-b558-4f31-8a80-7a50e73a4115"),
                            AccessFailedCount = 0,
                            Active = true,
                            ConcurrencyStamp = "88b527d2-0f63-4a55-80b0-bee9c71b68fb",
                            CreatedID = new Guid("aab46b7a-b558-4f31-8a80-7a50e73a4115"),
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "seller2@bshop.com",
                            EmailConfirmed = true,
                            FullName = "Carhat",
                            LockoutEnabled = false,
                            NormalizedEmail = "Seller2@BSHOP.COM",
                            NormalizedUserName = "SELLER2@BSHOP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENmR5O5XiC+fa+41jaqq6Of5K7PGJpA6FTT82jiiWhhkD04hH9wW71Y3iTpcTw39dg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4c8bcbc5-4537-4df6-8aa7-736bcf1002d5",
                            TwoFactorEnabled = false,
                            UserName = "Seller2@bshop.com"
                        },
                        new
                        {
                            Id = new Guid("59a2e5b0-a606-40c5-8cdb-bc90d947eef8"),
                            AccessFailedCount = 0,
                            Active = true,
                            ConcurrencyStamp = "37b04abe-5f6b-4d4b-a700-61d5a310d879",
                            CreatedID = new Guid("59a2e5b0-a606-40c5-8cdb-bc90d947eef8"),
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "seller3@bshop.com",
                            EmailConfirmed = true,
                            FullName = "Silvary",
                            LockoutEnabled = false,
                            NormalizedEmail = "Seller3@BSHOP.COM",
                            NormalizedUserName = "SELLER3@BSHOP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMPFb2knGowAxuhK9sxuyVC0P40QFeugoar21N/eabc7AmOMWHi8e5z4F17G51DmqQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7bc6d622-f996-4d83-aa6c-634520e27f53",
                            TwoFactorEnabled = false,
                            UserName = "Seller3@bshop.com"
                        },
                        new
                        {
                            Id = new Guid("44027cba-b38d-4308-83ae-eda59940d565"),
                            AccessFailedCount = 0,
                            Active = true,
                            ConcurrencyStamp = "d7da95e6-e469-45ea-ae68-84e1d59d2ea8",
                            CreatedID = new Guid("44027cba-b38d-4308-83ae-eda59940d565"),
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "seller4@bshop.com",
                            EmailConfirmed = true,
                            FullName = "Sobnil",
                            LockoutEnabled = false,
                            NormalizedEmail = "Seller4@BSHOP.COM",
                            NormalizedUserName = "SELLER4@BSHOP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO4LvnlPG6Fm2kivj2R7mwcu9/x8qor0oU43HrqpH8M+Js2FhaV2jl9GujRyutOuGg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0d8f0cab-cf0c-4f0c-b27e-d567141c4561",
                            TwoFactorEnabled = false,
                            UserName = "Seller4@bshop.com"
                        },
                        new
                        {
                            Id = new Guid("2abef967-f3b0-42b1-8398-9645494724de"),
                            AccessFailedCount = 0,
                            Active = true,
                            ConcurrencyStamp = "df4b9965-2f84-4a86-8456-10f893487331",
                            CreatedID = new Guid("2abef967-f3b0-42b1-8398-9645494724de"),
                            CreatedTime = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Customer@bshop.com",
                            EmailConfirmed = true,
                            FullName = "Customer",
                            LockoutEnabled = false,
                            NormalizedEmail = "CUSTOMER@BSHOP.COM",
                            NormalizedUserName = "CUSTOMER@BSHOP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKGi31AAsyydUXr589Ef44ZueWRC8MFzh8mh+hPo31K0YwUdgl7/WVhwEAUMjCW34w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0f41db6f-4a85-4d03-9a8d-fa39b8289327",
                            TwoFactorEnabled = false,
                            UserName = "Customer@bshop.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc"),
                            ConcurrencyStamp = "9cf2716e-b9ae-4b32-b882-8a94e4ee2ce8",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("96095fe3-5264-4047-a18b-b1e9e6d2931f"),
                            ConcurrencyStamp = "4fd986e6-376f-4865-9aa8-57465851ef87",
                            Name = "Seller",
                            NormalizedName = "SELLER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("b22698b8-42a2-4115-9631-1c2d1e2ac5f7"),
                            RoleId = new Guid("8d04dce2-969a-435d-bba4-df3f325983dc")
                        },
                        new
                        {
                            UserId = new Guid("c7bc5cc5-d2df-43e5-bf6e-95f88bb9ee6a"),
                            RoleId = new Guid("96095fe3-5264-4047-a18b-b1e9e6d2931f")
                        },
                        new
                        {
                            UserId = new Guid("aab46b7a-b558-4f31-8a80-7a50e73a4115"),
                            RoleId = new Guid("96095fe3-5264-4047-a18b-b1e9e6d2931f")
                        },
                        new
                        {
                            UserId = new Guid("59a2e5b0-a606-40c5-8cdb-bc90d947eef8"),
                            RoleId = new Guid("96095fe3-5264-4047-a18b-b1e9e6d2931f")
                        },
                        new
                        {
                            UserId = new Guid("44027cba-b38d-4308-83ae-eda59940d565"),
                            RoleId = new Guid("96095fe3-5264-4047-a18b-b1e9e6d2931f")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("BShop.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("BShop.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BShop.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("BShop.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
